Remove first run page, migrate to Chromium baseapp
flathub/com.google.Chrome pull request #117
Opened 2022-03-12 01:30 UTC by refi64

2022-03-12 01:51 UTC, TheEvilSkeleton commented on com.google.Chrome.yaml
> +base-version: '21.08'
```suggestion
base-version: 'master'
```

2022-03-12 04:45 UTC, TheEvilSkeleton commented
bot, build

2022-03-12 17:45 UTC, refi64 commented
bot, build

2022-03-13 15:58 UTC, TheEvilSkeleton approved these changes
Works for me.

2022-03-21 02:29 UTC, TheEvilSkeleton requested changes
Don't forget to remove unnecessary files

2022-03-30 00:28 UTC, merged